### ISSUE TITLE
Sentry 7

### ISSUE THREAD

**Issue by k4nar** [docker-library/sentry#6] opened 2015-02-04 09:57 UTC
The last version of this image uses Sentry 6.4.4. Sentry 7.0 has been released last January, and now the last version is 7.1.4.

Is there any plan to upgrade this image ?

**Comment by tianon** [comment] 2015-02-04 17:06
This is a duplicate of https://github.com/docker-library/sentry/pull/4.  Please contribute to the discussion over there.

**Closed by tianon** 2015-02-04 17:06 UTC

**Comment by k4nar** [comment] 2015-02-05 14:55
Sorry about that, I looked at the issues but not at the PRs.
